### ISSUE TITLE
 I can't get the song length to be correct

### ISSUE THREAD

**Issue by jpastorm** [jpastorm/gopifai-api-music-go#1]
Normally it should be obtained with the size of the song, but I cannot obtain the real one, my guess is that it gives me a wrong result because it takes all the size with the lyrics and the cover.

You can try any song you want, you just have to make sure that you point to a valid path with a song in mp3 format

GetTrack()
https://github.com/jpastorm/gopifai-api-music-go/blob/master/src/controllers/explorador.controller.go
![ScreenShot](https://i.ibb.co/XzKHbzG/issue.jpg)

![ScreenShot](https://i.ibb.co/LvpQBVs/issue2.png)

**Comment by binkkatal** [comment]
@jpastorm ,
maybe this article could help http://www.goat.cz/index.php?path=MP3_MP3ProfiInfo
